PUT http://localhost:8080/events/2
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzEzMDQwNjQ1LCJ1c2VySWQiOjJ9.NsfufyvM28t6eGqbDrbrPmfY0XOSlSex71fUemH4els

{
    "name": "Updated test event",
    "description": "An updated test event",
    "location": "Test location updated",
    "dateTime" : "2025-01-01T11:11:00Z"
}